### ISSUE TITLE
Use BLOB to store binary matrices within database

### ISSUE THREAD

**Issue by alexdawn** [AequilibraE/aequilibrae#118]
Despite the guidance suggesting this:

>Along with the Sqlite file that is the base for the AequilibraE project, other data such as documentation and binary matrices (OMX or AEM) do not fit nicely into a database structure, and therefore are stored in the file system in parallel with the Sqlite Project in a folder with the same name.

A table with filename and the files as BLOBs would work as storing matrix data within the sqlite database, additional tags and labels can be used to describe the matrix metadata

**Comment by pedrocamargo** [comment]
Hey @alexdawn .  I have already considered it, but this does not work with full-blown forecasting models due to the sheer number of matrices that would exist. If you imagine that you would have demand matrices on the various stages of the demand model and skims for multiple modes, and all that would exist for the multiple time periods being modeled and for multiple iterations of the model system.
For example:
- Model with 4,000 zones (pretty normal these days)
- Traffic modes only - 3 modes (car, light truck, heavy truck) - Assumes transit will be done using another tool, such as FastTrips
- Simplest demand model possible for a traffic-focused model (mode-specific gravity model for each mode)
- 4 time periods
- 4 iterations of the model system
- 3 (modes) * 4 (times) * 4 (iterations) * 122 Mb (64 bit matrix) = 5.7Gb

This is already a little too big for an SQLite database (makes it non-portable, really), and it is not even a proper model yet.
There is a reason why all commercial software packages keep matrices outside their databases and in separate files in the file system.
Does it make sense?
