### ISSUE TITLE
shapely dependencies issues

### ISSUE THREAD

**Issue by bstabler** [AequilibraE/aequilibrae#261]
I'm having a hard time getting the software to install on my computer.  I think its probably a dependencies chain consistency issue.  Below is what I tried on my Windows machine based on your getting started page.
 
  - conda create -n pedrotest python=3.8 (it doesn’t say use Anaconda but I don’t want to mess up my core Python install so I’m assuming this will work…)
  - activate pedrotest
  - pip install aequilibrae
  - pip install openmatrix
  - download and setup spatialist on my hard drive
  - start python and try this and then run into this error. 
 
        import os
        from aequilibrae.utils.create_example import create_example
 
 
![test](https://user-images.githubusercontent.com/5761221/121935489-559bd400-ccfd-11eb-891b-7fcc5d8cf9b5.png)

**Comment by janzill** [comment]
Hi @bstabler, I think you are right and this is probably due to using pip inside a conda virtual environment, see e.g. https://github.com/Toblerity/Shapely/issues/1032. Are you happy to use virtualenv and pip?

`python -m pip install virtualenv
virtualenv .venv
.venv\Scripts\activate.bat
`
This will create a .venv directory from wherever you run it. The last line where you activate the environment might be slightly wrong syntax-wise (I use my ubuntu distro on WSL when I'm on windows) but that's the script you need to run to activate. Then pip install should work without problems.

**Comment by janzill** [comment]
@bstabler it looks like this has been fixed in the latest shapely release (https://github.com/shapely/shapely/pull/1108, released on 26 Oct 2021 as v1.8.0) and you can now pip install shapely within a conda environment on windows

**Comment by pedrocamargo** [comment]
This was an upstream issue that seems to have been solved
